apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-banka
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/rima-gif/FrontDevSecOps'
    targetRevision: HEAD
    path: frontend-banka
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
